services:
  - type: web
    name: emoji-quiz
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py load_sample_quizzes"
    startCommand: "gunicorn emoji_quiz.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true